spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    time-zone: GMT+8

  #配置文件上传大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000Mb
      max-request-size: 5000Mb
  #  分布式session配置
  session:
    timeout: 43200s
  #freemarker配置
  freemarker:
    request-context-attribute: request

#flowable流程引擎配置
flowable:
  #关闭定时任务job
  async-executor-activate: false
  check-process-definitions: false
  common:
    app:
      idm-url: http://localhost:8080/flowable-idm
      role-prefix: ''
  modeler:
    app:
      rest-enabled: true
  rest:
    app:
      authentication-mode: verify-privilege

#文件上传下载配置
uploader:
  type: minio
  minio:
    bucket:
      lhy: suneee
    url: 172.19.7.102
    port: 9000
    accessKey: suneee
    secretKey: suneeeminio
    secure: false
    urlExpire: 86400
  localFs:
    storePath: /opt/data/eas
    url: http://dev.suneee.com/store
  s3:
    host: http://172.19.7.102
    port: 9000
    region: cn-north-1
    accessKey: suneee
    secretKey: suneeeminio
    singer: AWSS3V4SignerType
    bucket:
      lhy: lhy
      xy: suneee
      yn: yn
    urlExpire: 60


#文件柜处理
fs:
  docFile:
    departmentId: 2
    personalId: 4
    publicId: 3
    groupId: 6
    flowFileId: 40

#系统配置
system:
  #姓名模式，alias为字号模式，其他为姓名模式
  username-mode: alias
  #当前运行环境
  runtimeEnv: lhy