spring:
  #配置文件上传大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000Mb
      max-request-size: 5000Mb
  #  分布式session配置
  session:
    timeout: 43200s

#文件上传下载配置
uploader:
  type: minio
  minio:
    bucket:
      xy: suneee
      lhy: lhy
      yr: yr
    url: http://172.19.7.102
    port: 9000
    accessKey: suneee
    secretKey: suneeeminio
    urlExpire: 86400
  localFs:
    storePath: /opt/data/eas
    url: http://dev.suneee.com/store
  #minio云存储集成s3 配置
  s3:
    host: http://172.19.7.102
    port: 9000
    region: cn-north-1
    accessKey: suneee
    secretKey: suneeeminio
    singer: AWSS3V4SignerType
    bucket:
      lhy: lhy
      xy: suneee
      yn: yn
    urlExpire: 60

#系统配置
system:
  #姓名模式，alias为字号模式，其他为姓名模式
  username-mode: alias
  #超级管理员账号
  super-admin: admin

#用于分布式产生主键id,部署到不同的服务器时修改这个值，从1开始(正整数)
#不同的应用服务器（连接同一数据服务器）需要保证这个数不同，否则必然会产生重复ID。
genId:
  xy: 11
  lhy: 12
  yr: 13